// game
export const UPDATE_GAME = "UPDATE_GAME";
export const RESET_GAME = "RESET_GAME";
export const ROLLBACK_HISTORY = "ROLLBACK_HISTORY";
export const AI_TOGGLE = "AI_TOGGLE";
export const SET_GAME_STATUS = "SET_GAME_STATUS";
export const INCREASE_MOVE_COUNT = "INCREASE_MOVE_COUNT";
export const STORE_PARTIAL_MOVE = "STORE_PARTIAL_MOVE";

// device
export const SET_TOUCH_STATUS = "SET_TOUCH_STATUS";

// ui
export const STORE_DESTINATIONS = "STORE_DESTINATIONS";
export const SET_ANIMATION_PHASE = "SET_ANIMATION_PHASE";

// AI
export const UPDATE_AI_TREE = "UPDATE_AI_TREE";